In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({
                    'text': ['people watch campusx', 'campusx watch campusx', 'people write comment', 'campusx write comment'],
                    'output': [1, 1, 0, 0]
                })

df

                    text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

## Bag of Words  [UniGrams]

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
cv = CountVectorizer()

bow = cv.fit_transform(df['text'])

In [5]:
cv.vocabulary_

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [6]:
print(bow[0].toarray())  # people watch campusx

print(bow[1].toarray())  # campusx watch campusx

[[1 0 1 1 0]]
[[2 0 0 1 0]]

In [7]:
cv.transform(['campusx watch and write comment of campusx']).toarray()

array([[2, 1, 0, 1, 1]])

## N - Grams

In [8]:
cv = CountVectorizer(ngram_range=(2,2))  # Bigram

bow = cv.fit_transform(df['text'])

In [9]:
cv.vocabulary_

{'people watch': 2,
 'watch campusx': 4,
 'campusx watch': 0,
 'people write': 3,
 'write comment': 5,
 'campusx write': 1}

In [10]:
print(bow[0].toarray())  # people watch campusx

print(bow[1].toarray())  # campusx watch campusx

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]

In [11]:
cv.transform(['campusx watch and write comment of campusx']).toarray()

array([[1, 0, 0, 0, 0, 1]])

In [12]:
cv = CountVectorizer(ngram_range=(1,2))  # Unigram + Bigram

bow = cv.fit_transform(df['text'])

In [13]:
cv.vocabulary_

{'people': 4,
 'watch': 7,
 'campusx': 0,
 'people watch': 5,
 'watch campusx': 8,
 'campusx watch': 1,
 'write': 9,
 'comment': 3,
 'people write': 6,
 'write comment': 10,
 'campusx write': 2}

In [14]:
print(bow[0].toarray())  # people watch campusx

print(bow[1].toarray())  # campusx watch campusx

[[1 0 0 0 1 1 0 1 1 0 0]]
[[2 1 0 0 0 0 0 1 1 0 0]]

In [15]:
cv.transform(['campusx watch and write comment of campusx']).toarray()

array([[2, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1]])

In [16]:
cv = CountVectorizer(ngram_range=(3,3))  # Trigram

bow = cv.fit_transform(df['text'])

In [17]:
cv.vocabulary_

{'people watch campusx': 2,
 'campusx watch campusx': 0,
 'people write comment': 3,
 'campusx write comment': 1}

In [18]:
print(bow[0].toarray())  # people watch campusx

print(bow[1].toarray())  # campusx watch campusx

[[0 0 1 0]]
[[1 0 0 0]]

In [19]:
cv.transform(['campusx watch and write comment of campusx']).toarray()

array([[0, 0, 0, 0]])

In [20]:
cv = CountVectorizer(ngram_range=(1,3))  # Unigram + Bigram + Trigram

bow = cv.fit_transform(df['text'])

In [21]:
cv.vocabulary_

{'people': 6,
 'watch': 11,
 'campusx': 0,
 'people watch': 7,
 'watch campusx': 12,
 'people watch campusx': 8,
 'campusx watch': 1,
 'campusx watch campusx': 2,
 'write': 13,
 'comment': 5,
 'people write': 9,
 'write comment': 14,
 'people write comment': 10,
 'campusx write': 3,
 'campusx write comment': 4}

In [22]:
print(bow[0].toarray())  # people watch campusx

print(bow[1].toarray())  # campusx watch campusx

[[1 0 0 0 0 0 1 1 1 0 0 1 1 0 0]]
[[2 1 1 0 0 0 0 0 0 0 0 1 1 0 0]]

In [23]:
cv.transform(['campusx watch and write comment of campusx']).toarray()

array([[2, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1]])

## Tf - IDF

In [24]:
df

                    text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [27]:
tfidf = TfidfVectorizer()

tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [28]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['campusx' 'comment' 'people' 'watch' 'write']